name: Build images
on:
  push:
    paths:
      - '.github/**'
      - 'Builder/**'
      - 'Final/**'

env:
  TAG_NAME: 2.7.2-alpine

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build builder image
        working-directory: ./Builder
        run: docker build -t builder .

      - name: Build final image
        working-directory: ./Final
        run: docker build -t final .

      - name: Push the images to GitHub Container Registry
        if: github.ref == 'refs/heads/master'
        run: |
          echo ${{ $GITHUB_TOKEN }} | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin

          docker tag builder ghcr.io/legal-general-insurance/rails-base-builder:latest
          docker tag builder ghcr.io/legal-general-insurance/rails-base-builder:${{ env.TAG_NAME }}
          docker push ghcr.io/legal-general-insurance/rails-base-builder:latest
          docker push ghcr.io/legal-general-insurance/rails-base-builder:${{ env.TAG_NAME }}

          docker tag final ghcr.io/legal-general-insurance/rails-base-final:latest
          docker push ghcr.io/legal-general-insurance/rails-base-final:latest
          docker tag final ghcr.io/legal-general-insurance/rails-base-final:${{ env.TAG_NAME }}
          docker push ghcr.io/legal-general-insurance/rails-base-final:${{ env.TAG_NAME }}
